config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "articles#index"

  # resources :articles, only: [:index, :show, :new]
  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [ :show, :edit, :update, :destroy ]

  def index
    @articles = Article.all
  end

  def show
    @comment = @article.comments.new
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: "The article \"#{@article.title}\" has been created."
    else
      flash[:notice] = "Failed to create an article."
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: "The article \"#{@article.title}\" has been has been updated."
    else
      flash[:notice] = "Failed to update the article."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "The article \"#{@article.title}\"Z has been deleted."

    redirect_to root_path, status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article
  before_action :set_comment, only: [ :show, :edit, :update, :destroy ]
  
  def index
    @comments = @article.comments
  end

  def show; end

  def create
    @comment = @article.comments.create(comment_params)

    if @comment.save 
      redirect_to article_comments_path(@article), notice: "A comment has been has been posted."
    else
      flash[:notice] = "Failed to post a comment."
      render 'articles/show', status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to article_comments_path(@article), notice: "The comment has been has been updated."
    else
      flash[:notice] = "Failed to update the comment."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy
    redirect_to article_comments_path(@article), notice: "The comment has been has been deleted."
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
  
  def set_article
    @article = Article.find(params[:article_id])
  end

  def set_comment
    @comment = @article.comments.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %><br>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div style="color:red; font-style:italic"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div style="color:red; font-style:italic"><%= message %></div>
    <% end %>
  </div>

  <div class="submit">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1 class="text-3xl font-bold">Articles</h1>
<ul>
  <% @articles.each do |article| %>
    <li style="padding: 5px 0 5px 0;">
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>
<br>
<div class="new-article-btn"><%= link_to "+ New Article", new_article_path %></div>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

<br>
<%= link_to "<< Return to Home", articles_path %>

app/views/articles/show.html.erb
<div class="title-container">
  <h1><%= @article.title %></h1>
  <div>
    <%= link_to "Edit", edit_article_path(@article) %>
    <%= link_to "Delete", article_path(@article), 
      data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
      } 
    %>
  </div>
</div>

<div class="body"><%= @article.body %></div>

<br>

<%= link_to "Show all comments", article_comments_path(@article) %>

<br>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<br>
<%= link_to "<< Return to Home", articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<%= link_to "Edit", edit_article_comment_path(@article) %>
<%= link_to "Destroy Comment", [comment.article, comment], 
  data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } 
%>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @comment ] do |form| %>
  <div>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %><br>
    <% if @comment.errors[:commenter].any? %>
      <% @comment.errors.full_messages_for(:commenter).each do |message| %>
        <div style="color:red; font-style:italic"><%= message %></div>
      <% end %>
    <% end %>
  </div>
  
  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% if @comment.errors[:body].any? %>
      <% @comment.errors.full_messages_for(:body).each do |message| %>
        <div style="color:red; font-style:italic"><%= message %></div>
      <% end %>
    <% end %>
  </div>
  <div class="submit">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render "form" %>

app/views/comments/index.html.erb
<h2>Comments</h2>

<% @comments.each do |comment| %>
  <div style="background-color: white; padding: 20px; margin: 10px 0 10px 0; border-radius: 10px; box-shadow: 5px 5px lightgray">
    <p> Commenter: <%= comment.commenter %></p>
    <p> Comment: <%= comment.body %></p>
    <span style="padding: 0 10px 20px 0"><%= link_to "View", article_comment_path(@article, comment) =%></span>
    <span style="padding: 0 10px 20px 0"><%= link_to "Edit", edit_article_comment_path(@article, comment) =%></span>
    <span style="padding: 0 10px 20px 0">
      <%= link_to "Destroy", article_comment_path(@article, comment), 
        data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        }
      %>
    </span>
  </div>
<% end %>
<br>
<%= link_to "<< Return to article", @article %>

app/views/comments/show.html.erb
<p>
  <strong>Commenter:</strong>
  <%= @comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.body %>
</p>
<br>
<%= link_to "<< Return to all comments", article_comments_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="main-container">
      <% flash.each do |type, msg| %>
        <div class="notice">
          <%= msg %>
        </div>
      <% end %>
    
      <%= yield %>
    </div>
  </body>
</html>